# Provides Eigen3::Eigen — Eigen 3.4.0's headers, for Ceres (ADR-0017). Header-only: nothing is
# built.
#
# MPL-2.0, the scoped exception ADR-0015 records: accepted only for the Ceres-backed camera
# registration plugin, with EIGEN_MPL2_ONLY defined so that including any of Eigen's remaining
# LGPL-licensed code is a compile error rather than a silent relicensing. The definition is on the
# TARGET, so every compile that sees Eigen's headers carries it — Ceres' own sources included,
# which is what makes building Ceres the proof.
#
# Eigen's own CMakeLists.txt is deliberately NOT run: it configures BLAS/LAPACK subprojects, tests
# and documentation, none of which a header-only consumer needs. The archive is populated only
# (SOURCE_SUBDIR names a directory the archive does not have, so MakeAvailable adds nothing), and
# the target is declared here. Ceres asks `find_package(Eigen3 3.3 REQUIRED)`; a config and version
# file in CMAKE_FIND_PACKAGE_REDIRECTS_DIR, which find_package searches first, answer it with this
# copy, so no system Eigen of another version can satisfy it.
#
# Included by addCeres.cmake, so nothing is fetched unless the Ceres plugin is enabled; guarded so
# a second include is a no-op.

if(TARGET Eigen3::Eigen)
	return()
endif()

include(FetchContent)

set(LAIN_EIGEN_VERSION "3.4.0")
set(EIGEN_FILE "gitlab.com/libeigen/eigen/-/archive/${LAIN_EIGEN_VERSION}/eigen-${LAIN_EIGEN_VERSION}.tar.gz")

FetchContent_Declare(eigen
	URL           "https://${EIGEN_FILE}"
	DOWNLOAD_DIR  "${CMAKE_SOURCE_DIR}/.cache/fetch/${EIGEN_FILE}"
	SOURCE_SUBDIR "lain-populate-only"
)
FetchContent_MakeAvailable(eigen)

# IMPORTED, so its include directory is SYSTEM (lain's strict flags never fire on Eigen) and so a
# target that exports itself — Ceres installs an export set naming Eigen3::Eigen — may name it.
add_library(Eigen3::Eigen INTERFACE IMPORTED GLOBAL)
set_target_properties(Eigen3::Eigen PROPERTIES
	INTERFACE_INCLUDE_DIRECTORIES "${eigen_SOURCE_DIR}"
	INTERFACE_COMPILE_DEFINITIONS "EIGEN_MPL2_ONLY"
)

file(WRITE "${CMAKE_FIND_PACKAGE_REDIRECTS_DIR}/eigen3-config.cmake"
"# Generated by lain's cmake/addEigen.cmake: Eigen3::Eigen is already defined.\n"
"set(Eigen3_FOUND TRUE)\n"
)
file(WRITE "${CMAKE_FIND_PACKAGE_REDIRECTS_DIR}/eigen3-config-version.cmake"
"# Generated by lain's cmake/addEigen.cmake.\n"
"set(PACKAGE_VERSION \"${LAIN_EIGEN_VERSION}\")\n"
"if(PACKAGE_FIND_VERSION VERSION_GREATER PACKAGE_VERSION OR NOT PACKAGE_FIND_VERSION_MAJOR EQUAL 3)\n"
"  set(PACKAGE_VERSION_COMPATIBLE FALSE)\n"
"else()\n"
"  set(PACKAGE_VERSION_COMPATIBLE TRUE)\n"
"  if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)\n"
"    set(PACKAGE_VERSION_EXACT TRUE)\n"
"  endif()\n"
"endif()\n"
)

# ---- Distribution obligations -----------------------------------------------
# MPL-2.0 asks a redistributor to keep the licence with the code and to say where its corresponding
# source is (ADR-0015). Eigen is compiled into whatever includes it, so the texts travel with the
# binaries and the notice reaches whoever runs one (--licenses).
set(_eigen_notice_dir "${CMAKE_BINARY_DIR}/third-party/eigen")
file(MAKE_DIRECTORY "${_eigen_notice_dir}")
file(GLOB _eigen_licenses "${eigen_SOURCE_DIR}/COPYING.*")
foreach(_f IN LISTS _eigen_licenses)
	get_filename_component(_name "${_f}" NAME)
	configure_file("${_f}" "${_eigen_notice_dir}/${_name}" COPYONLY)
endforeach()

set(_eigen_notice "${CMAKE_BINARY_DIR}/notices/eigen.txt")
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/notices")
file(WRITE "${_eigen_notice}"
"Eigen ${LAIN_EIGEN_VERSION} — MPL-2.0\n"
"  This software uses Eigen (https://eigen.tuxfamily.org), unmodified, compiled with\n"
"  EIGEN_MPL2_ONLY so that no LGPL-licensed Eigen code is included.\n"
"  Corresponding source: https://${EIGEN_FILE}\n"
"  Full licence texts: third-party/eigen/\n")
set_property(GLOBAL APPEND PROPERTY LAIN_THIRD_PARTY_NOTICES "${_eigen_notice}")
